### ISSUE TITLE
Custom embed 

### ISSUE THREAD

**Issue by Akoummanos** [JackCrispy/fivem#12]
Hello everyone. Iam making a discord bot for my fivem rp server. I want to see the status from my server. I download a fivem library and i make a discord embed to send everytime when someone need it. But the problem is that it sends true or false everytime the server is up or down. I want to make a costum command. For example: When its up it wiil say Server is up✅. And when its down: Server is down🔞.
pictures of the embed:
![Screenshot_278](https://user-images.githubusercontent.com/80427001/111829949-06a8f300-88f6-11eb-9a65-e3ff1508d313.png)

The code:
    *module.exports = {*

    *  name:'status',*

    *  description: "information",*

    *  async execute(message, args, Discord){*

    *  const FiveM = require("fivem") // Import the npm package.*

    *  const srv = new FiveM.Server('ipport') // Set the IP with port.*

    *  const s = await srv.getServerStatus()*

    *  const p = await srv.getPlayers()*

    *    const newEmbed = new Discord.MessageEmbed()*

    *       .setColor('#c40000')*

    *        .setTitle('Server Status.')*

    *        .setAuthor('Roleplayname', '') *

    *        .addField(`Server status is: ${s}`, true)*

    *        .addField(`Players Online: ${p}`, true)*

    *        .setThumbnail('')*

    *        .setTimestamp()*

    *        message.channel.send(newEmbed);*

    *srv.getServerStatus().then(data => console.log(data)) // Get & log the data!*

    *srv.getPlayers().then(data => console.log(data));*

    *}*

    *}*

Thank you everyone.

**Comment by TickerDev** [comment]
Hi, I guess the problem is that you need to put a comma ','
.addField(`Players Online:`, p)
hope that help you

**Comment by realistiqrp** [comment]
> Hi, I guess the problem is that you need to put a comma ','
> .addField(`Players Online:`, p)
> hope that help you

This doesn't work at my code 😅

I have at this moment
```
.addFields(
{name: "FiveM Status:", value: "`" + currPlayers + "/" + maxPlayers + "`"}
)
```

Yes i defined the maxPlayers and the currPlayers but it the command reaction embed sends the following `[object Promise]/[object Promise]`


I defined the currPlayers and the maxPlayers like this:
```
const maxPlayers = srv.getPlayers()
const currPlayers = srv.getMaxPlayers()
```

**Comment by crispyaus** [comment]
it's a promise either use await or .then
