### ISSUE TITLE
Messages & Embeds

### ISSUE THREAD

**Issue by Justman10000** [JackCrispy/fivem#13]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
You can also write it in such a way that the recorded data can be sent as messages or embeds in channels! In the console, the data bring little!

**Describe alternatives you've considered**
Nothing

**Additional context**
...

**Comment by stefa-n** [comment]
try saving the data somewhere & then using it in an embed

**Comment by Justman10000** [comment]
> 
> 
> try saving the data somewhere & then using it in an embed

And how?

**Comment by stefa-n** [comment]
Make a global variable and then update it in a function
If you want to use it in embeds, you can do this: 
```js
.setAuthor(`${srv.getProjectName}`)
```
It is not necessary to use those examples.

**Comment by stefa-n** [comment]
(also, getProjectName is currently not available to you aswell, but I'll make a PR with the change I made because, well, license, and because I do not want to be a dick)

**Comment by Justman10000** [comment]
> (also, getProjectName is currently not available to you aswell, but I'll make a PR with the change I made because, well, license, and because I do not want to be a dick)

I have try this:

```javascript
function FM() {

    const FiveM_Embed = new MessageEmbed()
        .setColor('RANDOM')
        .setAuthor({
            name: guild.name,
            iconURL: guild.iconURL()
        })
        .setTitle(
            'FiveM Daten von ' + guild.name
        )
        .setFooter({
            text: guild.name,
            iconURL: guild.iconURL()
        })

    srv.getPlayers().then(
        data => {
            FiveM_Embed.setDescription(data)
        }
    )

    channel.send({
        embeds: [
            FiveM_Embed
        ]
    })
}

FM()
```

**Comment by Justman10000** [comment]
Nothing comes!

**Comment by ShreshthTiwari** [comment]
Its easy just make a module as
fivemFetcher.js
inside it use the function
srv.getServer()
and return all the values you need
for images it returns them in base64
so convert that base 64 into a png
and send it as an attachment to a channel
get that message and take out the url of the image
and set it as the thumbnail of your embed
