### ISSUE TITLE
getCurrentPlayers()

### ISSUE THREAD

**Issue by enriquebudiono** [JackCrispy/fivem#3]
When I run getCurrentPlayers() command, I got lot's of things. How can I only take the name only

**Comment by crispyaus** [comment]
Hey! the getCurrentPlayers() function is an array. It will list all the players names & identifiers on your server.

If you’d like to get the current players in a number you can do getPlayers()

Let me know if you have further questions.

**Comment by enriquebudiono** [comment]
When I’m using getCurrentPlayers(), i got steam identifiers, fivem license,
ip, name, etc. However, the only data that I’m willing to get is the name
only

**Comment by crispyaus** [comment]
You can map the array and only pull what you need, basic JavaScript bud.

**Comment by enriquebudiono** [comment]
I see thank you

**Comment by crispyaus** [comment]
No problem!
