### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Sattishh** [JackCrispy/fivem#5]
I was testing the API and I am wondering If I'm correct about my assumption.

I think that if I get ``Error: Request failed with status code 404``, It means that the IP is either incorrect or whitelisted?

Am I correct? Is there no way to get data of a whitelisted server?

**Comment by crispyaus** [comment]
Hey.

I’m not too sure, but you can go to http://your.ip/info.json to see. If it shows up and works then there’s probably an issue with the api or how you’re using it.

Thanks.

**Comment by Sattishh** [comment]
Alright, thanks for the info!
