### ISSUE TITLE
help plase

### ISSUE THREAD

**Issue by MohaIQ61** [JackCrispy/fivem#7]
When I do a command for my Discord bot it returns with "[object Promise]"

Please help

**Comment by crispyaus** [comment]
Hi. Which function are you using? Also remember to json stringify the response.

**Comment by MohaIQ61** [comment]
i used with discord Message Embed

**Comment by crispyaus** [comment]
ok so use toString(). for example let playercount = bla bla bla
then you do
let stringedplayercount = playercount.toString()

**Comment by MohaIQ61** [comment]
Cannot access 'playercount' before initialization     
    at Object.

**Comment by MohaIQ61** [comment]
the is my code

let stringedplayercount = playercount.toString()
let playercount = players
bot.on('message', msg => {
  if (msg.content === 'ip') {
    msg.reply(players);
  }
});

**Comment by MohaIQ61** [comment]
this my code

const Discord = require('discord.js');
const DATA = require('./config.json');
const bot = new Discord.Client();
const FiveM = require("fivem") 
const srv = new FiveM.Server('172.105.86.186:30120') 

 
srv.getPlayers().then(data => console.log(data))
srv.getServerStatus().then(data => console.log(data))
bot.on('ready', () => {
    var botData = [{
        Name: bot.user.tag,
        Server: bot.guilds.cache.size,
        Channels: bot.channels.cache.size,
        Onwer: `!MOHA#6969`
      }]
      console.table(botData)
});
let stringedplayercount = playercount.toString()
let playercount = players
bot.on('message', msg => {
  if (msg.content === 'ip') {
    msg.reply(players);
  }
});

bot.login(DATA.token);

**Comment by crispyaus** [comment]
So you're not defining players & playercount is below stringedplayercount.

Try this:

```
const Discord = require('discord.js');
const DATA = require('./config.json');
const bot = new Discord.Client();
const FiveM = require("fivem")
const srv = new FiveM.Server('172.105.86.186:30120')

srv.getPlayers().then(data => {
// srv.getServerStatus().then(data => console.log(data))

bot.on('ready', () => {

var botData = [{
Name: bot.user.tag,
Server: bot.guilds.cache.size,
Channels: bot.channels.cache.size,
Onwer: '!MOHA#6969'
}]
    console.table(botData)
});

let stringedplayercount = data.toString()

bot.on('message', msg => {
    if (msg.content === 'ip') {
    msg.reply(stringedplayercount);
    }
})
});

bot.login(DATA.token);```

**Comment by MohaIQ61** [comment]
The same is the case with the server state؟؟

**Comment by MohaIQ61** [comment]
thanks bro and sorry for my bad language

**Comment by crispyaus** [comment]
Did you resolve the issue?

**Comment by MohaIQ61** [comment]
Yeb but how can i make bot send server offline not online when the server is offline

**Comment by crispyaus** [comment]
You can setup a cron job. Search setup cron job discord.js.

Then run all your code inside that.
