### ISSUE TITLE
Cannot get Server status, when Server is offline.

### ISSUE THREAD

**Issue by xSehrMotiviert** [JackCrispy/fivem#9]
Hello,

I get an error, when I try to get the status of a server, which is offline or not on the given port.

Code: 

srv.getServerStatus(data => console.log(data));

Error:

(node:22360) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED XXX.XXX.XXX.XXX:30665
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
(node:22360) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by anthonygregis** [comment]
Same issue

**Comment by crispyaus** [comment]
Hi. this will be fixed in the next update

**Comment by crispyaus** [comment]
Closed via v2.1.5. Will now return { online: false } or { online: true }.

**Comment by crispyaus** [comment]
This was fixed in latest patch, getting reports of it erring again with connection resets, will investigate.
